ARG debian_buster_image_tag=8-jre-slim
FROM openjdk:${debian_buster_image_tag}

# -- Layer: OS + Python 3.7

ARG shared_workspace=/opt/workspace

RUN mkdir -p ${shared_workspace} && \
    apt-get update -y && \
    apt-get install -y python3 && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

ENV SHARED_WORKSPACE=${shared_workspace}

# -- Runtime

VOLUME ${shared_workspace}
CMD ["bash"]




# -- Layer: Apache Spark

ARG spark_version=3.0.0
ARG hadoop_version=2.7
ENV SPARK_HOME=/usr/local/spark


ENV PATH $PATH:$JAVA_HOME/bin
ENV PATH=$PATH:${SPARK_HOME}/bin

RUN apt-get update -y && \
    apt-get install -y curl && \
    curl https://archive.apache.org/dist/spark/spark-${spark_version}/spark-${spark_version}-bin-hadoop${hadoop_version}.tgz -o spark.tgz && \
    tar -xf spark.tgz && \
    mv spark-${spark_version}-bin-hadoop${hadoop_version} ${SPARK_HOME} && \
    mkdir ${SPARK_HOME}/logs && \
    rm spark.tgz


ENV SPARK_MASTER_HOST spark-master
ENV SPARK_MASTER_PORT 7077
ENV PYSPARK_PYTHON python3


 
COPY config/hive-site.xml ${SPARK_HOME}/conf/

# -- Runtime

WORKDIR ${SPARK_HOME}